name: Check code style and run test cases

on:
  push:
    branches:
      - master
      - uat
      - dev
  pull_request:
    branches:
      - master
      - uat
      - dev

jobs:
  linting:
    name: Check code style and run test cases
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4    
      - uses: actions/cache@v4
        with:
          path: storage/fonts/1649148690_vision_cursor.zip
          key: ${{ runner.os }}-new-cursor
          restore-keys: |
            ${{ runner.os }}-new-cursor
